- name: Install Docker, Terraform, and GitLab on Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
      register: apt_update

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Verify Docker Compose installation
      shell: docker-compose --version
      when: docker_compose_download_result|success

    - name: Install Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
        dest: /tmp/terraform.zip

    - name: Extract Terraform
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin/
        remote_src: yes
        creates: /usr/local/bin/terraform

    - name: Make Terraform executable
      file:
        path: /usr/local/bin/terraform
        mode: 'u+x'

    - name: Install GitLab
      docker_container:
        name: gitlab
        image: gitlab/gitlab-ce:latest
        restart_policy: always
        ports:
          - "80:80"
          - "443:443"
          - "22:22"
        volumes:
          - "/opt/gitlab/config:/etc/gitlab"
          - "/opt/gitlab/logs:/var/log/gitlab"
          - "/opt/gitlab/data:/var/opt/gitlab"







