- name: Install Docker, Terraform, and GitLab on Ubuntu
  hosts: localhost
  become: true

  tasks:
    - name: Install Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
      register: apt_update

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
